### PR TITLE
Update airports by IATA codes

### PR DESCRIPTION
**Pull request by ForeverProglamer**
Greetings! 

I am working on a project that uses different sources of airport information, including the following: 
- airportsdata
- Duffel: https://duffel.com/docs/api/v1/airports/get-airports
- Kiwi: https://tequila.kiwi.com/docs/tequila_api/locations_api 

Comparing airports by IATA codes between these sources I found that the data provided by airportsdata sometimes mismatches with the other two sources and with iata.org. Sometimes coordinates can be inaccurate/wrong, IATA code can be assigned to the wrong place, or IATA code was reassigned and airportsdata entry points to the old airport. So in this PR I would like to address this issue.

Each commit fixes one problematic entry. Check the commit body of each commit,  there I referenced different resources (iata.org, Wikipedia, etc.) that will help to understand made decisions.

### CODE REVIEW

**Comment by ForeverProglamer** [comment]
Aside from what I have committed so far, there is one more problematic entry with IATA code `SGG`. iata.org does not have any entries for this code https://www.iata.org/en/publications/directories/code-search/?airport.search=SGG. Kiwi and Wikipedia point to [this one](https://en.wikipedia.org/wiki/Sermiligaaq_Heliport). But, without information from iata.org I am not sure how this entry should be handled. 

As there are entries with empty IATA codes, I thought about just assigning an empty string for this entry until iata.org adds information on this IATA code.

**Comment by mborsetti** [comment]
Hello and sorry for the delay.  Wonderful contributions, thank you so much!!

> Aside from what I have committed so far, there is one more problematic entry with IATA code `SGG`. iata.org does not have any entries for this code https://www.iata.org/en/publications/directories/code-search/?airport.search=SGG. Kiwi and Wikipedia point to [this one](https://en.wikipedia.org/wiki/Sermiligaaq_Heliport). But, without information from iata.org I am not sure how this entry should be handled.
> 
> As there are entries with empty IATA codes, I thought about just assigning an empty string for this entry until iata.org adds information on this IATA code.

I am starting to doubt the freshness of IATA's information on that site; I have access to other (private) databases and can confirm that SGG is "SERMILIGAAQ, GREENLAND", so please do go ahead and contribute it.  I will then publish a new version.

THANKS so much!!

**Comment by ForeverProglamer** [comment]
> SGG is "SERMILIGAAQ, GREENLAND", so please do go ahead and contribute it

Done. I think the PR is ready for review.

**Review by mborsetti — APPROVED** [review]

**Review by mborsetti — APPROVED** [review]

**Review by mborsetti — APPROVED** [review]
Interesting ... https://skyvector.com/airport/FDSK/Sikhuphe-International-Airport has elevation at 1092 ft, as does the VFR chart.

**Review by mborsetti — APPROVED** [review]

**Review by mborsetti — APPROVED** [review]

**Review by mborsetti — APPROVED** [review]

**Review by mborsetti — APPROVED** [review]

**Review by mborsetti — APPROVED** [review]

**Pull request merged**
